<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Fides/Fides.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="RepositoryFiles.fs" />
    <Compile Include="LibraryTests.fs" />
    <Compile Include="RepositoryContext.fs" />
    <Compile Include="RepositoryContextTests.fs" />
    <Compile Include="TrustBoundaryModelTests.fs" />
    <Compile Include="RequirementsTraceability.fs" />
    <Compile Include="RequirementsTraceabilityTests.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
</Project>
