<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>EchelonFoundry.Fides</PackageId>
    <AssemblyName>Fides</AssemblyName>
    <RootNamespace>Fides</RootNamespace>
    <Description>Fides (Echelon Foundry).</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Library.fs" />
  </ItemGroup>
</Project>
